/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desafio;

import InterfacesSecundarias.NumsRomanos;
import InterfacesSecundarias.Numshexadecimales;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author javier
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * variables de clase
     */
    private ArrayList<String> lista_nums;
    private ArrayList<String> lista_caract;
    private String num;
    private int positionX, positionY;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        lista_nums = new ArrayList();
        lista_caract = new ArrayList();
        num = "";
        positionX = 0;
        positionY = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GRBsalida = new javax.swing.ButtonGroup();
        GRBentrada = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAsalida = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        PanelOperaciones = new javax.swing.JPanel();
        Bdividir = new javax.swing.JButton();
        Bretroceso = new javax.swing.JButton();
        Blimpiar = new javax.swing.JButton();
        Bmultiplicar = new javax.swing.JButton();
        Babrirllave = new javax.swing.JButton();
        Bcerrarllave = new javax.swing.JButton();
        Brestar = new javax.swing.JButton();
        Belevado = new javax.swing.JButton();
        Braiz = new javax.swing.JButton();
        Bsuma = new javax.swing.JButton();
        Bigual = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        B7 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B0 = new javax.swing.JButton();
        Bcoma = new javax.swing.JButton();
        Bmodulo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        RBdecimalEntrada = new javax.swing.JRadioButtonMenuItem();
        RBhexadecimalEntrada = new javax.swing.JRadioButtonMenuItem();
        RBoctalEntrada = new javax.swing.JRadioButtonMenuItem();
        RBromanoEntrada = new javax.swing.JRadioButtonMenuItem();
        RBescritoEntrada = new javax.swing.JRadioButtonMenuItem();
        RBbinarioEntrada = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        RBdecimalSalida = new javax.swing.JRadioButtonMenuItem();
        RBoctalSalida = new javax.swing.JRadioButtonMenuItem();
        RBhexadecimalSalida = new javax.swing.JRadioButtonMenuItem();
        RBromanoSalida = new javax.swing.JRadioButtonMenuItem();
        RBbinarioSalida = new javax.swing.JRadioButtonMenuItem();
        RBescritoSalida = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setPreferredSize(new java.awt.Dimension(328, 311));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        TAsalida.setColumns(20);
        TAsalida.setRows(5);
        TAsalida.setAutoscrolls(false);
        TAsalida.setEnabled(false);
        jScrollPane1.setViewportView(TAsalida);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        PanelOperaciones.setLayout(new java.awt.GridLayout(4, 3, 5, 5));

        Bdividir.setText("/");
        Bdividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdividirActionPerformed(evt);
            }
        });
        PanelOperaciones.add(Bdividir);

        Bretroceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/retroceso.png"))); // NOI18N
        Bretroceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BretrocesoActionPerformed(evt);
            }
        });
        PanelOperaciones.add(Bretroceso);

        Blimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/limpiar.png"))); // NOI18N
        Blimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlimpiarActionPerformed(evt);
            }
        });
        PanelOperaciones.add(Blimpiar);

        Bmultiplicar.setText("*");
        Bmultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmultiplicarActionPerformed(evt);
            }
        });
        PanelOperaciones.add(Bmultiplicar);

        Babrirllave.setText("(");
        Babrirllave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BabrirllaveActionPerformed(evt);
            }
        });
        PanelOperaciones.add(Babrirllave);

        Bcerrarllave.setText(")");
        Bcerrarllave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcerrarllaveActionPerformed(evt);
            }
        });
        PanelOperaciones.add(Bcerrarllave);

        Brestar.setText("-");
        Brestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrestarActionPerformed(evt);
            }
        });
        PanelOperaciones.add(Brestar);

        Belevado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/elevado.png"))); // NOI18N
        Belevado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BelevadoActionPerformed(evt);
            }
        });
        PanelOperaciones.add(Belevado);

        Braiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/raiz.png"))); // NOI18N
        Braiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BraizActionPerformed(evt);
            }
        });
        PanelOperaciones.add(Braiz);

        Bsuma.setText("+");
        Bsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsumaActionPerformed(evt);
            }
        });
        PanelOperaciones.add(Bsuma);

        Bigual.setText("=");
        Bigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BigualActionPerformed(evt);
            }
        });
        PanelOperaciones.add(Bigual);

        jPanel2.add(PanelOperaciones, java.awt.BorderLayout.EAST);

        jPanel4.setLayout(new java.awt.GridLayout(4, 3));

        B7.setText("7");
        B7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        B7.setFocusPainted(false);
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });
        jPanel4.add(B7);

        B2.setText("8");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jPanel4.add(B2);

        B9.setText("9");
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });
        jPanel4.add(B9);

        B4.setText("4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        jPanel4.add(B4);

        B5.setText("5");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        jPanel4.add(B5);

        B6.setText("6");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        jPanel4.add(B6);

        B1.setText("1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel4.add(B1);

        B8.setText("2");
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });
        jPanel4.add(B8);

        B3.setText("3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        jPanel4.add(B3);

        B0.setText("0");
        B0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0ActionPerformed(evt);
            }
        });
        jPanel4.add(B0);

        Bcoma.setText(",");
        Bcoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcomaActionPerformed(evt);
            }
        });
        jPanel4.add(Bcoma);

        Bmodulo.setText("%");
        Bmodulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmoduloActionPerformed(evt);
            }
        });
        jPanel4.add(Bmodulo);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jMenu1.setText("entrada");

        GRBentrada.add(RBdecimalEntrada);
        RBdecimalEntrada.setSelected(true);
        RBdecimalEntrada.setText("Decimal");
        RBdecimalEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBdecimalEntradaActionPerformed(evt);
            }
        });
        jMenu1.add(RBdecimalEntrada);

        GRBentrada.add(RBhexadecimalEntrada);
        RBhexadecimalEntrada.setText("Hexadecimal");
        RBhexadecimalEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBhexadecimalEntradaActionPerformed(evt);
            }
        });
        jMenu1.add(RBhexadecimalEntrada);

        GRBentrada.add(RBoctalEntrada);
        RBoctalEntrada.setText("Octal");
        RBoctalEntrada.setEnabled(false);
        jMenu1.add(RBoctalEntrada);

        GRBentrada.add(RBromanoEntrada);
        RBromanoEntrada.setText("Romano simplificado");
        RBromanoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBromanoEntradaActionPerformed(evt);
            }
        });
        jMenu1.add(RBromanoEntrada);

        GRBentrada.add(RBescritoEntrada);
        RBescritoEntrada.setText("Escrito");
        RBescritoEntrada.setToolTipText("separar los \"mil\" con \"-\"");
        RBescritoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBescritoEntradaActionPerformed(evt);
            }
        });
        jMenu1.add(RBescritoEntrada);

        GRBentrada.add(RBbinarioEntrada);
        RBbinarioEntrada.setText("Binario");
        RBbinarioEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBbinarioEntradaActionPerformed(evt);
            }
        });
        jMenu1.add(RBbinarioEntrada);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Informacion.png"))); // NOI18N
        jMenuItem1.setText("Información");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("salida");

        GRBsalida.add(RBdecimalSalida);
        RBdecimalSalida.setSelected(true);
        RBdecimalSalida.setText("Decimal");
        RBdecimalSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBdecimalSalidaActionPerformed(evt);
            }
        });
        jMenu2.add(RBdecimalSalida);

        GRBsalida.add(RBoctalSalida);
        RBoctalSalida.setText("Octal");
        RBoctalSalida.setEnabled(false);
        jMenu2.add(RBoctalSalida);

        GRBsalida.add(RBhexadecimalSalida);
        RBhexadecimalSalida.setText("Hexadecimal");
        RBhexadecimalSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBhexadecimalSalidaActionPerformed(evt);
            }
        });
        jMenu2.add(RBhexadecimalSalida);

        GRBsalida.add(RBromanoSalida);
        RBromanoSalida.setText("Romano");
        RBromanoSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBromanoSalidaActionPerformed(evt);
            }
        });
        jMenu2.add(RBromanoSalida);

        GRBsalida.add(RBbinarioSalida);
        RBbinarioSalida.setText("Binario");
        RBbinarioSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBbinarioSalidaActionPerformed(evt);
            }
        });
        jMenu2.add(RBbinarioSalida);

        GRBsalida.add(RBescritoSalida);
        RBescritoSalida.setText("Escrito");
        RBescritoSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBescritoSalidaActionPerformed(evt);
            }
        });
        jMenu2.add(RBescritoSalida);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        TAsalida.setText(TAsalida.getText() + "2");
        num += "2";
    }//GEN-LAST:event_B8ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        TAsalida.setText(TAsalida.getText() + "8");
        num += "8";
    }//GEN-LAST:event_B2ActionPerformed

    private void BmultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmultiplicarActionPerformed
        lista_nums.add(num);
        lista_caract.add("*");
        TAsalida.setText(TAsalida.getText() + "*");
        num = "";
    }//GEN-LAST:event_BmultiplicarActionPerformed

    private void B0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0ActionPerformed
        TAsalida.setText(TAsalida.getText() + "0");
        num += "0";
    }//GEN-LAST:event_B0ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        TAsalida.setText(TAsalida.getText() + "1");
        num += "1";
    }//GEN-LAST:event_B1ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        TAsalida.setText(TAsalida.getText() + "3");
        num += "3";
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        TAsalida.setText(TAsalida.getText() + "4");
        num += "4";
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        TAsalida.setText(TAsalida.getText() + "5");
        num += "5";
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        TAsalida.setText(TAsalida.getText() + "6");
        num += "6";
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        TAsalida.setText(TAsalida.getText() + "7");
        num += "7";
    }//GEN-LAST:event_B7ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        TAsalida.setText(TAsalida.getText() + "9");
        num += "9";
    }//GEN-LAST:event_B9ActionPerformed

    private void BcomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcomaActionPerformed
        TAsalida.setText(TAsalida.getText() + ",");
        num += ".";
    }//GEN-LAST:event_BcomaActionPerformed

    private void BmoduloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmoduloActionPerformed
        lista_nums.add(num);
        lista_caract.add("%");
        TAsalida.setText(TAsalida.getText() + "%");
        num = "";
    }//GEN-LAST:event_BmoduloActionPerformed

    private void BsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsumaActionPerformed
        lista_nums.add(num);
        lista_caract.add("+");
        TAsalida.setText(TAsalida.getText() + "+");
        num = "";
    }//GEN-LAST:event_BsumaActionPerformed

    private void BrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrestarActionPerformed
        lista_nums.add(num);
        lista_caract.add("-");
        TAsalida.setText(TAsalida.getText() + "-");
        num = "";
    }//GEN-LAST:event_BrestarActionPerformed

    private void BdividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdividirActionPerformed
        lista_nums.add(num);
        lista_caract.add("/");
        TAsalida.setText(TAsalida.getText() + "/");
        num = "";
    }//GEN-LAST:event_BdividirActionPerformed

    private void BigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BigualActionPerformed
        lista_nums.add(num);
        int notDecimal = 0;
        double decimal = 0.0;
        String solucion = "";
        try {
            if (RBdecimalEntrada.isSelected()) {
                num = "";
                if (RBdecimalSalida.isSelected()) {
                    solucion = operacion() + "";
                }
                if (RBoctalSalida.isSelected()) {
                    /*------------------------------------------------->
                Octal oct = new Octal(operacion());
                solucion = oct.decToOctal();
                     */
                }
                if (RBbinarioSalida.isSelected()) {
                    Binario bi = new Binario();
                    decimal = operacion();
                    notDecimal = (int) decimal;
                    solucion = bi.decimalToBinary(notDecimal);
                }
                if (RBescritoSalida.isSelected()) {
                    Decimal de = new Decimal();
                    decimal = operacion();
                    notDecimal = (int) decimal;
                    solucion = de.decimalToEscrito(notDecimal + "");
                }
                if (RBhexadecimalSalida.isSelected()) {
                    Hexadecimal he = new Hexadecimal();
                    decimal = operacion();
                    notDecimal = (int) decimal;
                    solucion = he.decimalToHex(notDecimal);
                }
                if (RBromanoSalida.isSelected()) {
                    Romano ro = new Romano();
                    decimal = operacion();
                    notDecimal = (int) decimal;
                    solucion = ro.decimalToRomano(notDecimal);
                }
            }
            if (RBoctalEntrada.isSelected()) {
                //++++++++++++++++++++++++++++
            }
            if (RBhexadecimalEntrada.isSelected()) {
                Hexadecimal he = new Hexadecimal();
                String numero = num+"";
                if (RBdecimalSalida.isSelected()) {
                    solucion = he.HexToDecimal(numero)+"";
                }
                if (RBoctalSalida.isSelected()) {
                    /*------------------------------------------------->
                     */
                }
                if (RBbinarioSalida.isSelected()) {
                    Binario bi = new Binario();
                    solucion = bi.decimalToBinary(he.HexToDecimal(numero))+"";
                }
                if (RBescritoSalida.isSelected()) {
                    Decimal de = new Decimal();
                    solucion = de.decimalToEscrito(he.HexToDecimal(numero)+"");
                }
                if (RBhexadecimalSalida.isSelected()) {
                    solucion = numero;
                }
                if (RBromanoSalida.isSelected()) {
                    Romano ro = new Romano();
                    solucion = ro.decimalToRomano(he.HexToDecimal(numero));
                }
            }
            if (RBromanoEntrada.isSelected()) {
                //-------------------------------------------------------------->aqui
            }
            if (RBescritoEntrada.isSelected()) {

            }
            if (RBbinarioEntrada.isSelected()) {

            }

            TAsalida.setText(solucion);
            lista_nums.clear();
            lista_caract.clear();
            num = solucion + "";
        } catch (Exception ex) {
            TAsalida.setText("Error");
        }
    }//GEN-LAST:event_BigualActionPerformed

    private void BabrirllaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BabrirllaveActionPerformed
        TAsalida.setText(TAsalida.getText() + "(");
    }//GEN-LAST:event_BabrirllaveActionPerformed

    private void BcerrarllaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcerrarllaveActionPerformed
        TAsalida.setText(TAsalida.getText() + ")");
    }//GEN-LAST:event_BcerrarllaveActionPerformed

    private void BretrocesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BretrocesoActionPerformed
        String nuevo_valor = "";
        String valor_antiguo = TAsalida.getText();
        for (int i = 0; i < valor_antiguo.length() - 1; i++) {
            nuevo_valor += valor_antiguo.charAt(i);
        }

        TAsalida.setText(nuevo_valor);
    }//GEN-LAST:event_BretrocesoActionPerformed

    private void BlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlimpiarActionPerformed
        lista_nums.clear();
        lista_caract.clear();
        TAsalida.setText("");
        num = "";
    }//GEN-LAST:event_BlimpiarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(null, "selecciona el tipo de valor que vas a introducir y el tipo\nal que quieres convertirlo"
                + "\nNota: en los valores escritos separa los miles por un guion ejemplo: tres-mil");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BelevadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BelevadoActionPerformed
        lista_nums.add(TAsalida.getText());
        lista_caract.add("^");
        TAsalida.setText(TAsalida.getText() + "^");
        num = "";
    }//GEN-LAST:event_BelevadoActionPerformed

    private void BraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BraizActionPerformed
        TAsalida.setText(TAsalida.getText() + "√");
        num = "√";
    }//GEN-LAST:event_BraizActionPerformed

    private void RBescritoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBescritoEntradaActionPerformed
        desactivarBotones();
    }//GEN-LAST:event_RBescritoEntradaActionPerformed

    private void RBromanoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBromanoEntradaActionPerformed
        desactivarBotones();
        NumsRomanos R = new NumsRomanos(this);
        R.setLocation(positionX + 328, positionY);
        R.setVisible(true);
    }//GEN-LAST:event_RBromanoEntradaActionPerformed

    private void RBbinarioEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBbinarioEntradaActionPerformed
        desactivarBotones();
        B2.setEnabled(false);
        B3.setEnabled(false);
        B4.setEnabled(false);
        B5.setEnabled(false);
        B6.setEnabled(false);
        B7.setEnabled(false);
        B8.setEnabled(false);
        B9.setEnabled(false);
    }//GEN-LAST:event_RBbinarioEntradaActionPerformed

    private void RBhexadecimalEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBhexadecimalEntradaActionPerformed
        desactivarBotones();
        Numshexadecimales he = new Numshexadecimales(this);
        he.setLocation(positionX + 328, positionY);
        he.setVisible(true);
    }//GEN-LAST:event_RBhexadecimalEntradaActionPerformed

    private void RBdecimalEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBdecimalEntradaActionPerformed
        if (RBdecimalSalida.isSelected()) {
            activarBotones();
        }
    }//GEN-LAST:event_RBdecimalEntradaActionPerformed

    private void RBhexadecimalSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBhexadecimalSalidaActionPerformed
        desactivarBotones();
    }//GEN-LAST:event_RBhexadecimalSalidaActionPerformed

    private void RBromanoSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBromanoSalidaActionPerformed
        desactivarBotones();
    }//GEN-LAST:event_RBromanoSalidaActionPerformed

    private void RBbinarioSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBbinarioSalidaActionPerformed
        desactivarBotones();
    }//GEN-LAST:event_RBbinarioSalidaActionPerformed

    private void RBescritoSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBescritoSalidaActionPerformed
        desactivarBotones();
    }//GEN-LAST:event_RBescritoSalidaActionPerformed

    private void RBdecimalSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBdecimalSalidaActionPerformed
        if (RBdecimalEntrada.isSelected()) {
            activarBotones();
        }
    }//GEN-LAST:event_RBdecimalSalidaActionPerformed

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        positionX = (int) this.getLocation().getX();
        positionY = (int) this.getLocation().getY();
    }//GEN-LAST:event_formComponentMoved

    /**
     * extraemos los numeros y la operacion a realizar
     *
     * @return devolvemos la solucion final
     */
    private Double operacion() {
        double solucion = 0.0;
        double num1 = 0.0;
        String raiz_num = "";
        String simbolo = "";
        for (int i = 0; i < lista_nums.size(); i++) {

            simbolo = "" + lista_nums.get(i).charAt(0);

            if (simbolo.equals("√")) {
                for (int j = 1; j < lista_nums.get(i).length(); j++) {
                    raiz_num += lista_nums.get(i).charAt(j);
                }
                num1 = Double.parseDouble(raiz_num);
                solucion = tipoOperacion(num1, solucion, i, "√");
            } else {
                num1 = Double.parseDouble(lista_nums.get(i));
                solucion = tipoOperacion(num1, solucion, i, "");
            }
        }
        return solucion;
    }

    /**
     * realizamos la operacion correspondiente
     *
     * @param num1 primer numero
     * @param num2 segundo numero
     * @param index indice del simbolo a mirar en el array
     * @param simbol simbolo de la operacion
     * @return
     */
    private Double tipoOperacion(double num1, double num2, int index, String simbol) {
        double solucion = 0.0;
        if (index > 0 && !simbol.equals("√")) {
            String simbolo = lista_caract.get(index - 1);
            switch (simbolo) {
                case "+":
                    solucion = num1 + num2;
                    break;
                case "-":
                    solucion = num1 - num2;
                    break;
                case "*":
                    solucion = num1 * num2;
                    break;
                case "/":
                    solucion = num2 / num1;
                    break;
                case "^":
                    solucion = Math.pow(num2, num1);
                    break;
                case "%":
                    solucion = num2 % num1;
                    break;
            }
        } else {
            if (simbol.equals("")) {
                solucion = num1;
            }
            if (simbol.equals("√") && index == 0) {
                solucion = Math.sqrt(num1);
            }
            if (simbol.equals("√") && index != 0) {
                num1 = (int) Math.sqrt(num1);
                String simbolo = lista_caract.get(index - 1);
                switch (simbolo) {
                    case "+":
                        solucion = num1 + num2;
                        break;
                    case "-":
                        solucion = num1 - num2;
                        break;
                    case "*":
                        solucion = num1 * num2;
                        break;
                    case "/":
                        solucion = num2 / num1;
                        break;
                    case "^":
                        solucion = Math.pow(num2, num1);
                        break;
                    case "%":
                        solucion = num2 % num1;
                        break;
                }
            }
        }
        return solucion;
    }

    /**
     * añadimos cualquier valor especial como puede ser en romano X o en
     * hexadecimal E...
     */
    public void addNumsEsp(String num) {
        TAsalida.append(num);
    }

    public void activarBotones() {
        Bcoma.setEnabled(true);
        Bdividir.setEnabled(true);
        Brestar.setEnabled(true);
        Bsuma.setEnabled(true);
        Bmodulo.setEnabled(true);
        Bmultiplicar.setEnabled(true);
        Babrirllave.setEnabled(true);
        Bcerrarllave.setEnabled(true);
        B2.setEnabled(true);
        B3.setEnabled(true);
        B4.setEnabled(true);
        B5.setEnabled(true);
        B6.setEnabled(true);
        B7.setEnabled(true);
        B8.setEnabled(true);
        B9.setEnabled(true);
    }

    public void desactivarBotones() {
        Bcoma.setEnabled(false);
        Bdividir.setEnabled(false);
        Brestar.setEnabled(false);
        Bsuma.setEnabled(false);
        Bmodulo.setEnabled(false);
        Bmultiplicar.setEnabled(false);
        Babrirllave.setEnabled(false);
        Bcerrarllave.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B0;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton Babrirllave;
    private javax.swing.JButton Bcerrarllave;
    private javax.swing.JButton Bcoma;
    private javax.swing.JButton Bdividir;
    private javax.swing.JButton Belevado;
    private javax.swing.JButton Bigual;
    private javax.swing.JButton Blimpiar;
    private javax.swing.JButton Bmodulo;
    private javax.swing.JButton Bmultiplicar;
    private javax.swing.JButton Braiz;
    private javax.swing.JButton Brestar;
    private javax.swing.JButton Bretroceso;
    private javax.swing.JButton Bsuma;
    private javax.swing.ButtonGroup GRBentrada;
    private javax.swing.ButtonGroup GRBsalida;
    private javax.swing.JPanel PanelOperaciones;
    private javax.swing.JRadioButtonMenuItem RBbinarioEntrada;
    private javax.swing.JRadioButtonMenuItem RBbinarioSalida;
    private javax.swing.JRadioButtonMenuItem RBdecimalEntrada;
    private javax.swing.JRadioButtonMenuItem RBdecimalSalida;
    private javax.swing.JRadioButtonMenuItem RBescritoEntrada;
    private javax.swing.JRadioButtonMenuItem RBescritoSalida;
    private javax.swing.JRadioButtonMenuItem RBhexadecimalEntrada;
    private javax.swing.JRadioButtonMenuItem RBhexadecimalSalida;
    private javax.swing.JRadioButtonMenuItem RBoctalEntrada;
    private javax.swing.JRadioButtonMenuItem RBoctalSalida;
    private javax.swing.JRadioButtonMenuItem RBromanoEntrada;
    private javax.swing.JRadioButtonMenuItem RBromanoSalida;
    private javax.swing.JTextArea TAsalida;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
