/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesSecundarias;

import desafio.Calculadora;

/**
 *
 * @author javier
 */
public class Numshexadecimales extends javax.swing.JFrame {

    /**
     * Creates new form Numshexadecimales
     */
    Calculadora calc;
    public Numshexadecimales() {
        initComponents();
        calc = null;
    }

    public Numshexadecimales(Calculadora c) {
        initComponents();
        calc = c;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BletraA = new javax.swing.JButton();
        BletraB = new javax.swing.JButton();
        BletraC = new javax.swing.JButton();
        BletraD = new javax.swing.JButton();
        BletraE = new javax.swing.JButton();
        BletraF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("numeros hexadecimales");
        setPreferredSize(new java.awt.Dimension(424, 65));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        BletraA.setText("A");
        BletraA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BletraAActionPerformed(evt);
            }
        });
        getContentPane().add(BletraA);

        BletraB.setText("B");
        BletraB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BletraBActionPerformed(evt);
            }
        });
        getContentPane().add(BletraB);

        BletraC.setText("C");
        BletraC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BletraCActionPerformed(evt);
            }
        });
        getContentPane().add(BletraC);

        BletraD.setText("D");
        BletraD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BletraDActionPerformed(evt);
            }
        });
        getContentPane().add(BletraD);

        BletraE.setText("E");
        BletraE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BletraEActionPerformed(evt);
            }
        });
        getContentPane().add(BletraE);

        BletraF.setText("F");
        BletraF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BletraFActionPerformed(evt);
            }
        });
        getContentPane().add(BletraF);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BletraBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BletraBActionPerformed
        calc.addNumsEsp("B");
    }//GEN-LAST:event_BletraBActionPerformed

    private void BletraAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BletraAActionPerformed
        calc.addNumsEsp("A");
    }//GEN-LAST:event_BletraAActionPerformed

    private void BletraCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BletraCActionPerformed
        calc.addNumsEsp("C");
    }//GEN-LAST:event_BletraCActionPerformed

    private void BletraDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BletraDActionPerformed
        calc.addNumsEsp("D");
    }//GEN-LAST:event_BletraDActionPerformed

    private void BletraEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BletraEActionPerformed
        calc.addNumsEsp("E");
    }//GEN-LAST:event_BletraEActionPerformed

    private void BletraFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BletraFActionPerformed
        calc.addNumsEsp("F");
    }//GEN-LAST:event_BletraFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Numshexadecimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Numshexadecimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Numshexadecimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Numshexadecimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Numshexadecimales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BletraA;
    private javax.swing.JButton BletraB;
    private javax.swing.JButton BletraC;
    private javax.swing.JButton BletraD;
    private javax.swing.JButton BletraE;
    private javax.swing.JButton BletraF;
    // End of variables declaration//GEN-END:variables
}
